config/routes.rb
SampleApp::Application.routes.draw do

  resources :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
   resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  This is a project developed at the University of Wisconsin-Madison in order to make a Twitter Clone based on Ruby on Rails.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact us at help@micromessage.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Send an e-mail to help@messageme.com
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
    <div class="row">
      <aside class="span4">
        <section>
          <%= render 'shared/user_info' %>
        </section>
        <section>
          <%= render 'shared/stats' %>
        </section>
        <section>
          <%= render 'shared/micropost_form' %>
        </section>
	</aside>
      <div class="span8">
        <h3 class= "user-name1">Messages</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
      <!--Sign in Portion if not already signed in --> 
<% else %>
    <div class="row">
    <div class="center col-md-8">
      <h1>Welcome to MessageMe</h1>
    </div>

  <div class="span3 col-md-4 offset4" >
    <%= form_for(:session, url: sessions_path) do |f| %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.submit "Sign in", class: "btn btn-large " %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path , {:style=>'color:#FF0000;'}%></p>
  </div>
  
</div>

    
<% end %>